/* eslint-disable @next/next/no-css-tags */
import Head from "next/head";
import Layout from "../components/Layout";
import Script from "next/script";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nigeria Logistic | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Script
        type="module"
        src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
      />
      <Script
        nomodule
        src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
      />
      <div>
        <Layout />
      </div>
    </div>
  );
}
